BASE_DIR = "/root/station/"

CONSTANTS_FILENAME = BASE_DIR + "constants.py"
SETTINGS_FILENAME = BASE_DIR + "settings.conf"
ID_FILENAME = BASE_DIR + "id.conf"
IP_ADDRESS_FILENAME = BASE_DIR + "ip_address.conf"
IBEACON_ID = "1E 02 01 06 1A FF 4C 00 02 15"

SEND_PACKET_PERIOD = 15.0
SEND_HEARTBEAT_PERIOD = 15.0
UPDATE_SETTINGS_PERIOD = 60.0
BROADCAST_PACKET_PERIOD = 5.0

RSSI_THRESHOLD = 0.07
NUMBER_LAST_RSSI_VALUES = 5

HCI_DEVICE = "hci0"

COMPANY_ID = "00 00"
BROADCAST_PACKET_ID = "AB AB"
IP_PACKET_ID = "CD CD"
IP_PACKET_END = "DE AD BE EF"
