CONSTANTS_FILENAME = "constants.py"
SETTINGS_FILENAME = "settings.conf"
ID_FILENAME = "id.conf"
IBEACON_ID = "1E 02 01 06 1A FF 4C 00 02 15"
WEBSERVER_IP = "http://192.168.1.30:3000"

SEND_PACKET_PERIOD = 5.0
SEND_HEARTBEAT_PERIOD = 15.0
UPDATE_SETTINGS_PERIOD = 60.0
BROADCAST_PACKET_PERIOD = 5.0

RSSI_THRESHOLD = 0.07
NUMBER_LAST_RSSI_VALUES = 5

HCI_DEVICE = "hci0"

COMPANY_ID = "00 00"
BROADCAST_PACKET_ID = "AB AB"
IP_PACKET_ID = "CD CD"
IP_PACKET_END = "DE AD BE EF"
